# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20180510_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(b'open', b'open'), (b'closed', b'closed')], max_length=6),
        ),
    ]
